var hierarchy =
[
    [ "AIS_ViewController", null, [
      [ "WidgetBlend", "class_widget_blend.html", [
        [ "WidgetDTGL", "class_widget_d_t_g_l.html", null ]
      ] ]
    ] ],
    [ "AspectBasic", "struct_aspect_basic.html", null ],
    [ "AspectVCMap", "struct_aspect_v_c_map.html", null ],
    [ "BaseLogger", "class_base_logger.html", null ],
    [ "BaseProgress", "class_base_progress.html", [
      [ "ProgressControl", "class_progress_control.html", null ]
    ] ],
    [ "siv::BasicPerlinNoise&lt; Float &gt;", "classsiv_1_1_basic_perlin_noise.html", null ],
    [ "BSplSurfParam", "struct_b_spl_surf_param.html", null ],
    [ "Buffer2DModeller", "class_buffer2_d_modeller.html", null ],
    [ "Buffer2DParam", "struct_buffer2_d_param.html", null ],
    [ "cesium::Cartographic", "classcesium_1_1_cartographic.html", null ],
    [ "CascadeMatrixRule", "struct_cascade_matrix_rule.html", null ],
    [ "CategoryType", "struct_category_type.html", null ],
    [ "ChannelFuseParam", "struct_channel_fuse_param.html", null ],
    [ "WeightedScoreRule::ClassScore", "struct_weighted_score_rule_1_1_class_score.html", null ],
    [ "ColorQuantityMap", "class_color_quantity_map.html", null ],
    [ "WeightedScoreRule::Condition", "struct_weighted_score_rule_1_1_condition.html", null ],
    [ "ModelTrainParam::DataConfig", "struct_model_train_param_1_1_data_config.html", null ],
    [ "dt::Descriptor", "structdt_1_1_descriptor.html", null ],
    [ "DTPluginInterface", "class_d_t_plugin_interface.html", null ],
    [ "EdgeWireItem", "struct_edge_wire_item.html", null ],
    [ "cesium::Ellipsoid", "classcesium_1_1_ellipsoid.html", null ],
    [ "ExportSystem", "class_export_system.html", null ],
    [ "Extrude3DModeller", "class_extrude3_d_modeller.html", null ],
    [ "Extrude3DParam", "struct_extrude3_d_param.html", null ],
    [ "FDIInterpModeller", "class_f_d_i_interp_modeller.html", null ],
    [ "FDIInterpParam", "struct_f_d_i_interp_param.html", null ],
    [ "FeatureExtractParam", "struct_feature_extract_param.html", null ],
    [ "FormulaOptimizeParam", "struct_formula_optimize_param.html", null ],
    [ "GeomPropAniso", "struct_geom_prop_aniso.html", null ],
    [ "GeomPropArc", "struct_geom_prop_arc.html", null ],
    [ "GeomPropAx3", "struct_geom_prop_ax3.html", null ],
    [ "GeomPropBBox", "struct_geom_prop_b_box.html", null ],
    [ "GeomPropBSpline", "struct_geom_prop_b_spline.html", null ],
    [ "GeomPropCircle", "struct_geom_prop_circle.html", null ],
    [ "GeomPropCone", "struct_geom_prop_cone.html", null ],
    [ "GeomPropCuboid", "struct_geom_prop_cuboid.html", null ],
    [ "GeomPropCylinder", "struct_geom_prop_cylinder.html", null ],
    [ "GeomPropLine", "struct_geom_prop_line.html", null ],
    [ "GeomPropPoint", "struct_geom_prop_point.html", null ],
    [ "GeomPropPolygon", "struct_geom_prop_polygon.html", null ],
    [ "GeomPropPolyline", "struct_geom_prop_polyline.html", null ],
    [ "GeomPropRect", "struct_geom_prop_rect.html", null ],
    [ "GeomPropSearch", "struct_geom_prop_search.html", null ],
    [ "GeomPropTrsf2d", "struct_geom_prop_trsf2d.html", null ],
    [ "GeomPropTrsf3d", "struct_geom_prop_trsf3d.html", null ],
    [ "util::GridProcessor&lt; GridType, OpType, IsConst &gt;", "structutil_1_1_grid_processor.html", null ],
    [ "util::GridProcessor&lt; GridType, OpType, true &gt;", "structutil_1_1_grid_processor_3_01_grid_type_00_01_op_type_00_01true_01_4.html", null ],
    [ "GSectionExtractor", "class_g_section_extractor.html", null ],
    [ "SemanticModel::HyperParams", "struct_semantic_model_1_1_hyper_params.html", null ],
    [ "IDWInterpModeller", "class_i_d_w_interp_modeller.html", null ],
    [ "IDWInterpParam", "struct_i_d_w_interp_param.html", null ],
    [ "IKInterpModeller", "class_i_k_interp_modeller.html", null ],
    [ "IKInterpParam", "struct_i_k_interp_param.html", null ],
    [ "ImageBndVtrModeller", "class_image_bnd_vtr_modeller.html", null ],
    [ "ImageBndVtrParam", "struct_image_bnd_vtr_param.html", null ],
    [ "ImageCropModeller", "class_image_crop_modeller.html", null ],
    [ "ImageCropParam", "struct_image_crop_param.html", null ],
    [ "ImageFilterParam", "struct_image_filter_param.html", null ],
    [ "ImageFlattenModeller", "class_image_flatten_modeller.html", null ],
    [ "ImageFlattenParam", "struct_image_flatten_param.html", null ],
    [ "ImageFuseModeller", "class_image_fuse_modeller.html", null ],
    [ "ImageFuseParam", "struct_image_fuse_param.html", null ],
    [ "ImageMergeParam", "struct_image_merge_param.html", null ],
    [ "ImageMorphParam", "struct_image_morph_param.html", null ],
    [ "ImageReprojectModeller", "class_image_reproject_modeller.html", null ],
    [ "ImageReprojectParam", "struct_image_reproject_param.html", null ],
    [ "ImageSubstractModeller", "class_image_substract_modeller.html", null ],
    [ "ImageSubstractParam", "struct_image_substract_param.html", null ],
    [ "ImportSystem", "class_import_system.html", null ],
    [ "ImTexture", "struct_im_texture.html", null ],
    [ "JudgeImage", "struct_judge_image.html", null ],
    [ "KDTreeImpl", "class_k_d_tree_impl.html", null ],
    [ "KRGInterpModeller", "class_k_r_g_interp_modeller.html", null ],
    [ "KRGInterpParam", "struct_k_r_g_interp_param.html", null ],
    [ "LearnModeller", "class_learn_modeller.html", null ],
    [ "LicenseManager::LicenseInfo", "struct_license_manager_1_1_license_info.html", null ],
    [ "LicenseManager", "class_license_manager.html", null ],
    [ "LimitBind", "struct_limit_bind.html", null ],
    [ "graph::Link", "structgraph_1_1_link.html", null ],
    [ "MarginalBind", "struct_marginal_bind.html", null ],
    [ "cv::Mat_&lt; _Tp &gt;", "classcv_1_1_mat__.html", null ],
    [ "cesium::Math", "classcesium_1_1_math.html", null ],
    [ "CascadeMatrixRule::MatrixStage", "struct_cascade_matrix_rule_1_1_matrix_stage.html", null ],
    [ "MDEMMSolidsModeller", "class_m_d_e_m_m_solids_modeller.html", null ],
    [ "MDEMMSolidsParam", "struct_m_d_e_m_m_solids_param.html", null ],
    [ "MeshBooleanModeller", "class_mesh_boolean_modeller.html", null ],
    [ "MeshBooleanParam", "struct_mesh_boolean_param.html", null ],
    [ "MeshDEMSolidModeller", "class_mesh_d_e_m_solid_modeller.html", null ],
    [ "MeshDEMSolidParam", "struct_mesh_d_e_m_solid_param.html", null ],
    [ "MeshDEMSurfaceModeller", "class_mesh_d_e_m_surface_modeller.html", null ],
    [ "MeshDEMSurfaceParam", "struct_mesh_d_e_m_surface_param.html", null ],
    [ "MeshRemeshModeller", "class_mesh_remesh_modeller.html", null ],
    [ "MeshRemeshParam", "struct_mesh_remesh_param.html", null ],
    [ "MeshRemoveCapModeller", "class_mesh_remove_cap_modeller.html", null ],
    [ "MeshRemoveCapParam", "struct_mesh_remove_cap_param.html", null ],
    [ "MileageSystem", "class_mileage_system.html", null ],
    [ "MileProjModeller", "class_mile_proj_modeller.html", null ],
    [ "util::MinMaxVoxel&lt; TreeType &gt;", "classutil_1_1_min_max_voxel.html", null ],
    [ "MMeshFVExtractor", "class_m_mesh_f_v_extractor.html", null ],
    [ "ModelPredictParam", "struct_model_predict_param.html", null ],
    [ "ModelTrainParam", "struct_model_train_param.html", null ],
    [ "MSectionExtractor", "class_m_section_extractor.html", null ],
    [ "MSourceSequence", "struct_m_source_sequence.html", null ],
    [ "MultiMeshFromVolume", "struct_multi_mesh_from_volume.html", null ],
    [ "graph::Node", "structgraph_1_1_node.html", null ],
    [ "ax::NodeEditor::Utilities::NodeBuilder", "structax_1_1_node_editor_1_1_utilities_1_1_node_builder.html", null ],
    [ "graph::NodeIdLess", "structgraph_1_1_node_id_less.html", null ],
    [ "NormalizeParam", "struct_normalize_param.html", null ],
    [ "OSGMClippingModeller", "class_o_s_g_m_clipping_modeller.html", null ],
    [ "OSGMClippingParam", "struct_o_s_g_m_clipping_param.html", null ],
    [ "OSGMRasterModeller", "class_o_s_g_m_raster_modeller.html", null ],
    [ "OSGMRasterParam", "struct_o_s_g_m_raster_param.html", null ],
    [ "ParamExtractor", "class_param_extractor.html", null ],
    [ "ParamFromAGPRaw", "struct_param_from_a_g_p_raw.html", null ],
    [ "graph::Pin", "structgraph_1_1_pin.html", null ],
    [ "Pipe3DModeller", "class_pipe3_d_modeller.html", null ],
    [ "Pipe3DParam", "struct_pipe3_d_param.html", null ],
    [ "PointsExtractor", "class_points_extractor.html", null ],
    [ "PointsFromStructures", "struct_points_from_structures.html", null ],
    [ "PSectionExtractor", "class_p_section_extractor.html", null ],
    [ "QMainWindow", null, [
      [ "Application", "class_application.html", null ],
      [ "WidgetPython", "class_widget_python.html", null ],
      [ "WidgetView", "class_widget_view.html", null ]
    ] ],
    [ "QObject", null, [
      [ "Document", "class_document.html", null ],
      [ "GraphSystem", "class_graph_system.html", null ],
      [ "ProgressControl", "class_progress_control.html", null ],
      [ "qtimgui::ImGuiRenderer", "classqtimgui_1_1_im_gui_renderer.html", null ]
    ] ],
    [ "QOpenGLExtraFunctions", null, [
      [ "qtimgui::ImGuiRenderer", "classqtimgui_1_1_im_gui_renderer.html", null ]
    ] ],
    [ "QOpenGLFunctions", null, [
      [ "WidgetGraph", "class_widget_graph.html", null ]
    ] ],
    [ "QOpenGLWidget", null, [
      [ "WidgetBlend", "class_widget_blend.html", null ],
      [ "WidgetGraph", "class_widget_graph.html", null ]
    ] ],
    [ "QProxyStyle", null, [
      [ "DarkStyle", "class_dark_style.html", null ]
    ] ],
    [ "QTableWidget", null, [
      [ "WidgetTable", "class_widget_table.html", null ]
    ] ],
    [ "QTabWidget", null, [
      [ "WidgetConfigMath", "class_widget_config_math.html", null ],
      [ "WidgetConfigRules", "class_widget_config_rules.html", null ],
      [ "WidgetConfigTypes", "class_widget_config_types.html", null ],
      [ "WidgetReportsGroup", "class_widget_reports_group.html", null ]
    ] ],
    [ "QtCustomEdit", null, [
      [ "WidgetSegments", "class_widget_segments.html", null ],
      [ "WidgetSegmentsGroup", "class_widget_segments_group.html", null ]
    ] ],
    [ "QTreeWidget", null, [
      [ "WidgetTree", "class_widget_tree.html", null ]
    ] ],
    [ "QuantityColorMap", "class_quantity_color_map.html", null ],
    [ "QuaterClipModeller", "class_quater_clip_modeller.html", null ],
    [ "QuaterClipParam", "struct_quater_clip_param.html", null ],
    [ "QWebEnginePage", null, [
      [ "AiWebEnginePage", "class_ai_web_engine_page.html", null ]
    ] ],
    [ "QWebEngineView", null, [
      [ "WidgetChat", "class_widget_chat.html", null ]
    ] ],
    [ "QWidget", null, [
      [ "ProjectItemWidget", "class_project_item_widget.html", null ],
      [ "ProjectsWidget", "class_projects_widget.html", null ],
      [ "SlicerSlider", "class_slicer_slider.html", null ],
      [ "WidgetCategory", "class_widget_category.html", null ],
      [ "WidgetClassRule", "class_widget_class_rule.html", null ],
      [ "WidgetClipping", "class_widget_clipping.html", null ],
      [ "WidgetColorBar", "class_widget_color_bar.html", null ],
      [ "WidgetConfigEditor", "class_widget_config_editor.html", null ],
      [ "WidgetConfigGraph", "class_widget_config_graph.html", null ],
      [ "WidgetConfigScene", "class_widget_config_scene.html", null ],
      [ "WidgetConfigSketch", "class_widget_config_sketch.html", null ],
      [ "WidgetContinuous", "class_widget_continuous.html", null ],
      [ "WidgetExport", "class_widget_export.html", null ],
      [ "WidgetFormula", "class_widget_formula.html", null ],
      [ "WidgetMethod", "class_widget_method.html", null ],
      [ "WidgetParams", "class_widget_params.html", [
        [ "WidgetReportParam", "class_widget_report_param.html", null ],
        [ "WidgetSequence", "class_widget_sequence.html", null ]
      ] ],
      [ "WidgetProp", "class_widget_prop.html", null ],
      [ "WidgetReport", "class_widget_report.html", null ],
      [ "WidgetSlicer", "class_widget_slicer.html", null ]
    ] ],
    [ "RBFInterpModeller", "class_r_b_f_interp_modeller.html", null ],
    [ "RBFInterpParam", "struct_r_b_f_interp_param.html", null ],
    [ "RegionSequence", "struct_region_sequence.html", null ],
    [ "RelationShip", "struct_relation_ship.html", null ],
    [ "ReportJudge", "struct_report_judge.html", null ],
    [ "ReportSequence", "struct_report_sequence.html", null ],
    [ "ResultAssignParam", "struct_result_assign_param.html", null ],
    [ "Revolve3DParam", "struct_revolve3_d_param.html", null ],
    [ "Ring2DModeller", "class_ring2_d_modeller.html", null ],
    [ "Ring2DParam", "struct_ring2_d_param.html", null ],
    [ "RockMileFusion", "struct_rock_mile_fusion.html", null ],
    [ "RockMileFusionModeller", "class_rock_mile_fusion_modeller.html", null ],
    [ "SceneAnimation", "struct_scene_animation.html", null ],
    [ "SceneCameraView", "struct_scene_camera_view.html", null ],
    [ "SceneConfig", "struct_scene_config.html", null ],
    [ "SceneOrbitObject", "struct_scene_orbit_object.html", null ],
    [ "SceneViewportCamera", "struct_scene_viewport_camera.html", null ],
    [ "SceneViewportConfig", "struct_scene_viewport_config.html", null ],
    [ "SectionFromGroup", "struct_section_from_group.html", null ],
    [ "SectionFromMesh", "struct_section_from_mesh.html", null ],
    [ "SectionFromShapes", "struct_section_from_shapes.html", null ],
    [ "SectionFromVolume", "struct_section_from_volume.html", null ],
    [ "SemanticSegments::Segment", "struct_semantic_segments_1_1_segment.html", null ],
    [ "SemanticCategory", "struct_semantic_category.html", null ],
    [ "SemanticConfig", "struct_semantic_config.html", null ],
    [ "SemanticCovar", "struct_semantic_covar.html", null ],
    [ "SemanticDetect", "struct_semantic_detect.html", null ],
    [ "SemanticFeatureSet", "struct_semantic_feature_set.html", null ],
    [ "SemanticFormula", "struct_semantic_formula.html", null ],
    [ "SemanticGeoRef", "struct_semantic_geo_ref.html", null ],
    [ "SemanticGroup", "struct_semantic_group.html", null ],
    [ "SemanticHeader", "struct_semantic_header.html", null ],
    [ "SemanticInterp", "struct_semantic_interp.html", null ],
    [ "SemanticInterval", "struct_semantic_interval.html", null ],
    [ "SemanticItemRep", "struct_semantic_item_rep.html", null ],
    [ "SemanticLabelSet", "struct_semantic_label_set.html", null ],
    [ "SemanticLimits", "struct_semantic_limits.html", null ],
    [ "SemanticMarginal", "struct_semantic_marginal.html", null ],
    [ "SemanticModel", "struct_semantic_model.html", null ],
    [ "SemanticParamSet", "struct_semantic_param_set.html", null ],
    [ "SemanticReveal", "struct_semantic_reveal.html", null ],
    [ "SemanticRule", "struct_semantic_rule.html", null ],
    [ "SemanticScalars&lt; Scalar &gt;", "struct_semantic_scalars.html", null ],
    [ "SemanticSegments", "struct_semantic_segments.html", null ],
    [ "SemanticStatistic", "struct_semantic_statistic.html", null ],
    [ "SemanticStratums", "struct_semantic_stratums.html", null ],
    [ "SemanticTexIds", "struct_semantic_tex_ids.html", null ],
    [ "SemanticTexture", "struct_semantic_texture.html", null ],
    [ "SemanticVariants", "struct_semantic_variants.html", null ],
    [ "SemanticVMapIds", "struct_semantic_v_map_ids.html", null ],
    [ "ShapeBooleanModeller", "class_shape_boolean_modeller.html", null ],
    [ "ShapeBooleanParam", "struct_shape_boolean_param.html", null ],
    [ "SingleMeshFromShape", "struct_single_mesh_from_shape.html", null ],
    [ "SingleMeshFromVolume", "struct_single_mesh_from_volume.html", null ],
    [ "SMeshFSExtractor", "class_s_mesh_f_s_extractor.html", null ],
    [ "SMeshFVExtractor", "class_s_mesh_f_v_extractor.html", null ],
    [ "StratumBind", "struct_stratum_bind.html", null ],
    [ "StratumSolidModeller", "class_stratum_solid_modeller.html", null ],
    [ "StratumSolidParam", "struct_stratum_solid_param.html", null ],
    [ "StratumSurfaceModeller", "class_stratum_surface_modeller.html", null ],
    [ "StratumSurfaceParam", "struct_stratum_surface_param.html", null ],
    [ "StructureDrill", "struct_structure_drill.html", null ],
    [ "StructureImage", "struct_structure_image.html", null ],
    [ "StructureLabel", "struct_structure_label.html", null ],
    [ "StructureMesh", "struct_structure_mesh.html", null ],
    [ "StructureOSGM", "struct_structure_o_s_g_m.html", null ],
    [ "StructurePoints", "struct_structure_points.html", null ],
    [ "StructureSection", "struct_structure_section.html", null ],
    [ "StructureShape", "struct_structure_shape.html", null ],
    [ "StructureSpine", "struct_structure_spine.html", null ],
    [ "StructureVolume", "struct_structure_volume.html", null ],
    [ "SttAttFusionModeller", "class_stt_att_fusion_modeller.html", null ],
    [ "SttClipSequence", "struct_stt_clip_sequence.html", null ],
    [ "SurfaceModeller", "class_surface_modeller.html", null ],
    [ "ToolCGAL", "class_tool_c_g_a_l.html", null ],
    [ "ToolColor", "class_tool_color.html", null ],
    [ "ToolDrill", "class_tool_drill.html", null ],
    [ "ToolFS", "class_tool_f_s.html", null ],
    [ "ToolGDAL", "class_tool_g_d_a_l.html", null ],
    [ "ToolGeom", "class_tool_geom.html", null ],
    [ "ToolImage", "class_tool_image.html", null ],
    [ "ToolKDTree&lt; Type &gt;", "class_tool_k_d_tree.html", null ],
    [ "ToolMesh", "class_tool_mesh.html", null ],
    [ "ToolMileage", "class_tool_mileage.html", null ],
    [ "ToolOCCT", "class_tool_o_c_c_t.html", null ],
    [ "ToolOSGB", "class_tool_o_s_g_b.html", null ],
    [ "ToolStat", "class_tool_stat.html", null ],
    [ "ToolString", "class_tool_string.html", null ],
    [ "ToolUVCoord", "class_tool_u_v_coord.html", null ],
    [ "ToolVDB", "class_tool_v_d_b.html", null ],
    [ "TopoMergeModeller", "class_topo_merge_modeller.html", null ],
    [ "TopoMergeParam", "struct_topo_merge_param.html", null ],
    [ "cesium::Transforms", "classcesium_1_1_transforms.html", null ],
    [ "UpdateFusionModeller", "class_update_fusion_modeller.html", null ],
    [ "WidgetConfigScene::ViewportWidgets", "struct_widget_config_scene_1_1_viewport_widgets.html", null ],
    [ "VlmDemFusion", "struct_vlm_dem_fusion.html", null ],
    [ "VlmDemFusionModeller", "class_vlm_dem_fusion_modeller.html", null ],
    [ "VlmSttAttFusion", "struct_vlm_stt_att_fusion.html", null ],
    [ "VlmUpdateFusion", "struct_vlm_update_fusion.html", null ],
    [ "VolumeBaseExtractor", "class_volume_base_extractor.html", null ],
    [ "VolumeClipping", "struct_volume_clipping.html", null ],
    [ "VolumeDoClipping", "class_volume_do_clipping.html", null ],
    [ "VolumeDrillParse", "class_volume_drill_parse.html", null ],
    [ "VolumeFromDrill", "struct_volume_from_drill.html", null ],
    [ "VolumeFromGroup", "struct_volume_from_group.html", null ],
    [ "VolumeFromMesh", "struct_volume_from_mesh.html", null ],
    [ "VolumeMergeExtractor", "class_volume_merge_extractor.html", null ],
    [ "VoxelModellerBase", "class_voxel_modeller_base.html", null ],
    [ "VSectionExtractor", "class_v_section_extractor.html", null ],
    [ "WeightedScoreRule", "struct_weighted_score_rule.html", null ],
    [ "qtimgui::WindowWrapper", "classqtimgui_1_1_window_wrapper.html", null ],
    [ "Wire3DModeller", "class_wire3_d_modeller.html", null ],
    [ "Wire3DParam", "struct_wire3_d_param.html", null ],
    [ "WireClampModeller", "class_wire_clamp_modeller.html", null ],
    [ "WireClampParam", "struct_wire_clamp_param.html", null ]
];